//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaOASIS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int NoFactura { get; set; }
        public int NoAutorizacion { get; set; }
        public int CodMed { get; set; }
        public int CantMed { get; set; }
        public int Precio { get; set; }
        public int CodUsuario { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Medicamento Medicamento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
